### ISSUE TITLE
Summary?

### ISSUE THREAD

**Issue by fuzzy76** [harperreed/zooooom.us#12]
There is nothing on the website (or in this repo) that explains what this is. It's a screensaver, and some sort of Zoom parody... but how? What does it do? I would like to know before installing.

**Comment by harperreed** [comment]
it is exactly as your described. A screensaver that is a zoom parody. Sorry there isn't more than that. Will consider how to make it more explanatory

**Comment by fuzzy76** [comment]
I was just unsure wether this was something more (like all screensaver users to a random zoom meeting. But I was to curious and had to install and test it. :)
